name: Deploy Java Spring Boot Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: |
          cd ai-ransomware-backend
          mvn clean install -DskipTests

      - name: Run Backend Server
        run: |
          cd ai-ransomware-backend/target
          java -jar ai-ransomware-backend.jar
